import clsx from 'clsx';
import type { Metadata } from 'next';
import { Sora } from 'next/font/google';
import './globals.css';

export const metadata: Metadata = {
  title: 'Company Profile',
  description: 'Landing Page Generated by create next app',
};

const sora = Sora({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal'],
  variable: '--font-sora',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(sora.variable, 'antialiased')}>{children}</body>
    </html>
  );
}
